const productos = [
    {
        id: 1,
        nombre: "Blusa Floral",
        precio: 850,
        imagen: "imagenes/blusa1.jpg",
        categoria: "Blusas",
        artesana: "Información pendiente",
        tecnica: "Punto de cruz",
        tiempo: "Tiempo aproximado pendiente",
        material: "Manta de algodón",
        descripcion: "Blusa artesanal bordada cuidadosamente a mano.",
        tallas: ["S", "M", "L", "XL"],
        colores: ["Rosa", "Blanco", "Turquesa", "Rojo"],
        coloresPedido: true
    },
    {
        id: 2,
        nombre: "Blusa Primavera",
        precio: 780,
        imagen: "imagenes/blusa2.jpg",
        categoria: "Huipiles/Ternos",
        artesana: "Información pendiente",
        tecnica: "Bordado artesanal",
        tiempo: "Tiempo aproximado pendiente",
        material: "Algodón",
        descripcion: "Prenda artesanal inspirada en las flores de la región.",
        tallas: ["S", "M", "L"],
        colores: ["Amarillo", "Blanco", "Verde"],
        coloresPedido: true
    },
    {
        id: 3,
        nombre: "Blusa Tradición",
        precio: 920,
        imagen: "imagenes/blusa3.jpg",
        categoria: "Guayaberas",
        artesana: "Información pendiente",
        tecnica: "Punto de cruz",
        tiempo: "Tiempo aproximado pendiente",
        material: "Manta de algodón",
        descripcion: "Diseño tradicional elaborado con detalles únicos.",
        tallas: ["M", "L", "XL"],
        colores: ["Rosa", "Rojo", "Blanco"],
        coloresPedido: true
    },
    {
        id: 4,
        nombre: "Blusa Maya",
        precio: 850,
        imagen: "imagenes/blusa4.jpg",
        categoria: "Rebozos",
        artesana: "Información pendiente",
        tecnica: "Bordado a mano",
        tiempo: "Tiempo aproximado pendiente",
        material: "Algodón",
        descripcion: "Una pieza que representa la identidad cultural de X-Pichil.",
        tallas: ["S", "M", "L", "XL"],
        colores: ["Turquesa", "Rosa", "Blanco"],
        coloresPedido: true
    },
    {
        id: 5,
        nombre: "Huipil Flor del Mayab",
        precio: 1100,
        imagen: "imagenes/blusa5.jpg",
        categoria: "Solapas",
        artesana: "Información pendiente",
        tecnica: "Punto de cruz",
        tiempo: "Tiempo aproximado pendiente",
        material: "Manta de algodón",
        descripcion: "Huipil artesanal con motivos inspirados en la naturaleza.",
        tallas: ["M", "L", "XL"],
        colores: ["Blanco", "Rosa", "Verde"],
        coloresPedido: true
    },
    {
        id: 6,
        nombre: "Blusa Jardín",
        precio: 890,
        imagen: "imagenes/blusa6.jpg",
        artesana: "Información pendiente",
        tecnica: "Bordado floral",
        tiempo: "Tiempo aproximado pendiente",
        material: "Algodón",
        descripcion: "Diseño lleno de color elaborado mediante técnicas tradicionales.",
        tallas: ["S", "M", "L"],
        colores: ["Rojo", "Turquesa", "Verde"],
        coloresPedido: true
    },
    {
        id: 7,
        nombre: "Huipil Tradicional",
        precio: 1250,
        imagen: "imagenes/blusa7.jpg",
        artesana: "Información pendiente",
        tecnica: "Bordado artesanal",
        tiempo: "Tiempo aproximado pendiente",
        material: "Manta",
        descripcion: "Prenda tradicional con acabados realizados cuidadosamente.",
        tallas: ["M", "L", "XL"],
        colores: ["Blanco", "Rojo", "Rosa"],
        coloresPedido: true
    },
    {
        id: 8,
        nombre: "Blusa Colores de X-Pichil",
        precio: 950,
        imagen: "imagenes/blusa8.jpg",
        artesana: "Información pendiente",
        tecnica: "Punto de cruz",
        tiempo: "Tiempo aproximado pendiente",
        material: "Algodón",
        descripcion: "Una pieza inspirada en los colores y la cultura de X-Pichil.",
        tallas: ["S", "M", "L", "XL"],
        colores: ["Turquesa", "Rosa", "Rojo", "Verde"],
        coloresPedido: true
    }
];